name: Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7]
        torch-version: [1.13.0.dev20220613+cu113]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}
        run: |
          pip install torch==${{ matrix.torch-version}} -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

      - name: Install main package
        run: |
          pip install -e .[test]

      - name: Run test-suite
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: success()
        with:
          fail_ci_if_error: false
